version: '3'

services:
  laravel-app:
    build:
      context: '.'
    container_name: laravel-app
    volumes:
      - ./src/:/var/www/html
    ports:
      - 18080:8080
    environment:
      - APP_DEBUG=1
      - APP_ENV=development
      - APP_KEY=base64:xQ6Ox2CT0SfW03QwbzX2U+Jda/G7uR2Sqcpd0I3HdAI=
      - DB_HOST=mysql-db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=laravel
      - LOG_CHANNEL=errorlog
      - SESSION_DRIVER=database

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel